source 'https://rubygems.org'

gem 'sinatra'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'capybara'
gem 'rake'
gem 'rspec'
gem 'rubocop-rspec'
gem 'rubocop'
gem 'coveralls'
gem 'launchy'
gem 'database_cleaner'